### ISSUE TITLE
not work at moodle3.8

### ISSUE THREAD

**Issue by FreeLanceCoder2020** [smart-twists/zarinpal_moodle_enrol_plugin#1]
سلام
.بعد از پرداخت و برگشت به صفحه درس ثبت نام انجام نمی شود.

**Comment by MobinDev** [comment]
comment line `26` in this file `public_html/enrol/zarinpal/verify.php`.
eventslib.php removed in moodle 3.6 !!!

**Comment by saeedsajadi** [comment]
Please submit a pull request
